// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {registry} from '../models';

export function CreateNewFile(arg1:string):Promise<registry.File>;

export function OpenFilePicker():Promise<string>;
